### ISSUE TITLE
执行完最后一个方法是不是不用调onCompleted

### ISSUE THREAD

**Issue by hito-zhang** [soulqw/WorkFlow#2]
会报java.lang.ArrayIndexOutOfBoundsException: Array index out of range

**Comment by soulqw** [comment]
@taoczZYC  要调用的，每个节点本身不知道自己是不是最后一个，因为执行顺序是在外部控制的，另外，你可以贴一下使用代码和出错堆栈，我帮你看下问题

**Comment by hito-zhang** [comment]
![WeChat23e9037625d18d5899eca1c1f69f6795](https://user-images.githubusercontent.com/11548042/80439439-1e236a00-8939-11ea-9c68-272abbfc74a7.png)
![WeChatd71a1afd7346ae5b178e1c0079df18bc](https://user-images.githubusercontent.com/11548042/80439446-1fed2d80-8939-11ea-9880-ac464ab4bc6c.png)
@soulqw

**Comment by soulqw** [comment]
@taoczZYC 按照你的描述我写了个代码似乎没有这个问题，我初步怀疑可能跟SparseArray 在不同系统的表现有点关系：
你尝试着：
1换个不同系统的手机，或者用手机模拟器跑跑demo试试
2.如果能稳定复现，在demo中的lib尝试着：
将 WorkFLow 中 143行 flowNodes.valueAt(nextIndex) 加入tryCatch 试试，异常将nextNode赋为Null试试
3.确认ok能解决的话 欢迎修改源码提PR

**Comment by smileToWxm** [comment]
下载了demo，其中，after和simple_test，执行均会报ArrayIndexOutOfBoundsException，根据报错查询在findAndExecuteNextNodeIfExist()的flowNodes.valueAt(nextIndex)，没有做越界判断导致了异常。

**Comment by soulqw** [comment]
@smileToWxm  如果按照上述的问题你解决了的话，欢迎在源码中修改并提PR

**Comment by smileToWxm** [comment]
![image](https://user-images.githubusercontent.com/49085555/80676247-efe48c80-8ae8-11ea-8798-d2348b26e9fb.png)
我是加了层逻辑判断就可以了

**Comment by soulqw** [comment]
@taoczZYC @smileToWxm  
最新0.0.3 已经解决上述bug
